#!/bin/bash

# use 'chunkc' to send message to socket
export CHUNKC_SOCKET=4131

chunkc config global_space_mode           bsp
chunkc config 2_space_mode            monocle
chunkc config 5_space_mode              float

chunkc config global_space_offset_top      60
chunkc config global_space_offset_bottom   50
chunkc config global_space_offset_left     50
chunkc config global_space_offset_right    50
chunkc config global_space_offset_gap      15

chunkc config 1_space_offset_top          200
chunkc config 1_space_offset_bottom       190
chunkc config 1_space_offset_left         190
chunkc config 1_space_offset_right        190
chunkc config 1_space_offset_gap           25

chunkc config 3_space_offset_top          200
chunkc config 3_space_offset_bottom       190
chunkc config 3_space_offset_left         190
chunkc config 3_space_offset_right        190

chunkc config bsp_spawn_left                1
chunkc config bsp_optimal_ratio         1.618
chunkc config bsp_split_mode          optimal
chunkc config bsp_split_ratio             0.5

chunkc config mouse_follows_focus           1
chunkc config window_float_next             0

# signal dock to make windows topmost when floated
# requires chwm-sa (https://github.com/koekeishiya/chwm-sa)
chunkc config window_float_topmost          1
